version: '3'

services: 
    app:
        build:
            context: .
            dockerfile: Dockerfile

        container_name: micro-api-app
        environment: 
            - APP_ENV=development
        
        ports: 
            - 3000:3000
